### ISSUE TITLE
Lacking "utils" files

### ISSUE THREAD

**Issue by Wastedzz** [paulffm/Discrete-Time-Diffusion-Models-for-Discrete-Data#1]
Cool for the implementation! But when I try to run the codes, the error occurs: "ModuleNotFoundError: No module named 'lib.utils.utils'". The same error occurs for the absence of "networks/network_utils.py". Can you resolve this issue?

**Comment by paulffm** [comment]
Thanks for reaching out!  The necessary files have been added, and the repository should now be complete. Please pull the latest changes from the `main` branch and try running the code again. If you encounter any further issues or have any other questions, feel free to let me know!
